filter:
    paths: [src/*]
    excluded_paths: [.docksal/*, vendor/*, tests/*, examples/*]
tools:
    external_code_coverage: true
    php_pdepend: true
    sensiolabs_security_checker: true
    php_loc:
        enabled: true
    php_cpd:
        enabled: true
    php_cs_fixer:
        enabled: true
        config: { level: psr2 }
